services:
  app:
    image: duplicatebooru
    build:
      context: .
    ports:
    - '8080:8080'
    volumes:
    - '.:/app'
    environment:
      PYTHONASYNCIODEBUG: "1"
      REDIS_URL: "redis://redis:6379/0"
      PORT: "8080"
      DANBOORU_API_KEY:
      DANBOORU_USERNAME:
      DANBOORU_USER_ID:
      DEBUG:
  redis:
    image: redis:8
